version: "3.9"
services:
  acar:
    build:
      context: .
      dockerfile: acar.Dockerfile
    image: git.uwaterloo.ca:5050/watonomous/registry/action-classification/acar
    volumes:
      - /mnt/wato-drive/road:/road
      - ./:/project/action-classification
      #- ../3D-RetinaNet:/project/3D-RetinaNet
      #- ../road-dataset:/project/road-dataset
      #- /proc:/host_proc
    ipc: host
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '1'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]


