version: "3.9"
services:
  acar:
    build:
      context: .
      dockerfile: acar.Dockerfile
    image: git.uwaterloo.ca:5050/watonomous/registry/action-classification/acar
    volumes:
      - /mnt/wato-drive/road:/road
      - ./modules/ACAR-Net:/project/ACAR-Net
    ipc: host
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '1'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]

  ocsort:
    build:
      context: .
      dockerfile: ocsort.Dockerfile
    image: git.uwaterloo.ca:5050/watonomous/registry/action-classification/ocsort
    volumes:
      - /mnt/wato-drive/road:/road
      - ./modules/OC-SORT:/project/OC-SORT
    ipc: host
    tty: true

  builder:
    build:
      context: .
      dockerfile: builder.Dockerfile
    image: git.uwaterloo.ca:5050/watonomous/registry/action-classification/video-builder
    volumes:
      - /mnt/wato-drive/road:/road
      - ./modules/Video-Builder:/project/Video-Builder
    ipc: host
    tty: true

  post:
    build:
      context: .
      dockerfile: post.Dockerfile
    image: git.uwaterloo.ca:5050/watonomous/registry/action-classification/post-processing
    volumes:
      - /mnt/wato-drive/road:/road
      - ./modules/Post-Processing:/project/Post-Processing
    ipc: host
    tty: true