evaluate: True #False 
result_path: ./output/text # same for any experiment in dvc world
tensorboard_path: ./output/tensorboard
model_path: ./output/saved_models # where the model is saved
resume_path: ckpt_6.pth.tar
manual_seed: 1
print_freq: 20
dataset: "road"
experiment_name: "test_changes"
# node * processes per node = # of cores that will be allocated
# we have one node, but can have multiple processes per node to take advantage of
# multiple GPU training (1 GPU per process). Resource: https://yangkky.github.io/2019/07/08/distributed-pytorch-tutorial.html 
nproc_per_node: 1

class_list: ["Red", "Amber", "Green",
"MovAway", "MovTow",
"Mov", "Rev", "Brake", "Stop", 
"IncatLft", "IncatRht", "HazLit", 
"TurLft", "TurRht", 
"MovRht", "MovLft", "Ovtak", 
"Wait2X", "XingFmLft", "XingFmRht", "Xing", "PushObj"]
        

model:
    freeze_bn: True
    backbone:
        arch: slowfast50
        learnable: True
        pretrain:
            path: /road/acar_models/SLOWFAST_R50_K400.pth.tar
        kwargs:
            alpha: 4
            beta: 0.125
            fuse_only_conv: False
            fuse_kernel_size: 7
            slow_full_span: True
    neck:
        type: basic
        kwargs:
            bbox_jitter:
                num: 1
                scale: 0.075
            num_classes: 22
            multi_class: True
    head:
        type: acar
        kwargs:
            width: 2304
            roi_spatial: 7
            num_classes: 22
            depth: 2

loss:
    type: ava_criterion
    kwargs:
        pose_softmax: True

train:
    root_path: /road/rgb-images
    annotation_path: /road/road_trainval_v1.0.json
    class_idx_path: /road/class_name_gen_1.json
    batch_size: 8
    workers: 8
        
    augmentation:
        spatial:
          - type: Scale
            kwargs:
                resize: 256
          - type: RandomHorizontalFlip
          - type: ToTensor
            kwargs:
                norm_value: 255.
          - type: Normalize
            kwargs:
                mean: [0.450, 0.450, 0.450]
                std: [0.225, 0.225, 0.225]
        temporal:
            type: TemporalCenterCrop
            kwargs:
                size: 64
                step: 2

    n_epochs: 10
    val_freq: 1
    save_freq: 1

    optimizer:
        type: SGD
        kwargs:
            momentum: 0.9
            weight_decay: 0.0000001
            nesterov: True
        
    scheduler:
        type: step
        milestone_epochs: [5.6, 5.8]
        lr_mults: [0.1, 0.1]
        base_lr: 0.008
        warmup_lr: 0.064
        warmup_epochs: 1

val:
    root_path: /road/rgb-images
    annotation_path: /road/road_trainval_v1.0.json
    # detection annotation path: /road/detections/val1_coco.jsonl
    class_idx_path: /road/class_name_gen_1.json
    # Maxes all ram and about half of GPUs on thor
    # batch_size: 24
    # workers: 20
    batch_size: 8
    workers: 8
    
    augmentation:
        spatial:
          - type: Scale
            kwargs:
                resize: 256
          - type: ToTensor
            kwargs:
                norm_value: 255.
          - type: Normalize
            kwargs:
                mean: [0.450, 0.450, 0.450]
                std: [0.225, 0.225, 0.225]
        temporal:
            type: TemporalCenterCrop
            kwargs:
                size: 64
                step: 2

    with_label: False
    eval_mAP:
        labelmap: /road/road_trainval_v1.0.json
        groundtruth: /road/road_trainval_v1.0.json